### ISSUE TITLE
Did not receive messages?

### ISSUE THREAD

**Issue by eArabic** [phhpro/easy-mail#1]
Hello dear friend, I tried to test this script, I do not know why it did not receive messages.
Do I make the same edits in easy-comments: /membri/bok
Thank you very much,  You are a professional and I like everything you program in php

**Comment by phhpro** [comment]
Huh? I recall just closing another issue where you said it was all working fine.

**Comment by phhpro** [comment]
Ouch, sorry. This applies to Easy Mail. Please post back your configuration along with a summary which might help to reproduce the error, thank you.

**Comment by phhpro** [comment]
OK, for the sake of simplicity... Had a quick fly-over and pushed an update. Please try again.

**Comment by eArabic** [comment]
Thank you so much my dear friend
Now it works after editing here:

![4](https://user-images.githubusercontent.com/24383546/34530740-2242e90c-f0c1-11e7-8b93-1f274342b81f.png)
![1](https://user-images.githubusercontent.com/24383546/34530741-2267e2d4-f0c1-11e7-8e36-4a7639759b2a.png)

**Comment by eArabic** [comment]
Thanks a lot, you've tried the new version now and it works as well.
thank you very much

**Comment by phhpro** [comment]
Welcome.
